### ISSUE TITLE
运行python z_server.py遇到错误，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [warriorpaw/z-ssl-proxy#1]
hi.

root@AR:~/z-ssl-proxy# python z_server.py
2016-02-28 19:49:17 INFO     loading config from /root/z-ssl-proxy/config.json
Traceback (most recent call last):
  File "z_server.py", line 358, in <module>
    main()
  File "z_server.py", line 341, in main
    server = myssl.ThreadingzProxyServer((SERVER,PORT[0]),
TypeError: 'int' object has no attribute '**getitem**'
root@AR:~/z-ssl-proxy#

**Comment by warriorpaw** [comment]
哦，当时把本地端配置文件改成多IP，但是服务端没动，导致配置文件格式不一致；
时间长没用都忘记了，直接传上来了。已改。
